disabled_rules:
- cyclomatic_complexity
- file_length
- function_body_length
- function_parameter_count
- line_length
- nesting
- type_body_length
opt_in_rules:
- attributes
attributes:
  always_on_line_above: ["@objc"]
